config/routes.rb
Rails.application.routes.draw do
  resources :items, only: :index

  resources :shops, only: [:new, :index, :create] do
    resources :reports, only: :create
  end
  resource :search, only: :show

  resource :signup
  resource :session
  resource :verification

  resources :users, only: :show

  root to: 'shops#index'
end

app/models/shop.rb
class Shop < ActiveRecord::Base
  CIVCRAFT_SERVER_PATTERN = /mc\.civcraft\.co|149\.56\.23\.82/
  LOCALHOST = /(127.0.0.1|localhost)/

  include PgSearch

  attr_accessor :server_address

  validates :output_item_name, :output_amount, :input_item_name, :input_amount,
    :world_uuid, :location_x, :location_y, :location_z, :which,
    :exchanges_available, presence: true
  validates :world_uuid, inclusion: {in: World.ids}
  validate :server_is_test_or_civcraft

  belongs_to :output_item, class_name: 'Item'
  belongs_to :input_item, class_name: 'Item'
  has_many :reports

  after_save do
    IndexedShop.index_shop self
  end

  scope :best, -> { order('reports_count ASC') }

  pg_search_scope :search, against: [:input_item_name, :output_item_name, :city, :seller_username]

  def self.safely_create(params)
    location_params = params.slice(
      :world, :location_x, :location_y, :location_z, :which)
    where(location_params).first_or_initialize.tap do |shop|
      transaction do
        shop.update_attributes!(params)
        shop.reports.destroy_all
      end
    end
  end

  def output_item_name=(name)
    super
    items = Item.named(name)
    self.output_item = items.first if items.any?
  end

  def input_item_name=(name)
    super
    items = Item.named(name)
    self.input_item = items.first if items.any?
  end

  def world
    World.find(world_uuid)
  end

  private

  def server_is_test_or_civcraft
    return if server_address.blank?

    unless server_address =~ Regexp.union(CIVCRAFT_SERVER_PATTERN, LOCALHOST)
      errors.add(:server_address, "You can only list Civcraft shops")
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  protect_from_forgery except: :create

  def new
    @shop = Shop.new
  end

  def index
    @shops = Shop.best.page(params[:page])


    respond_to do |format|
      format.html do
        @shops = ShopsDecorator.decorate(@shops)
      end
      format.json do
        render json: @shops
      end
    end
  end

  def create
    @shop = Shop.safely_create(shop_params)

    respond_to do |format|
      if @shop.persisted?
        format.html do
          flash[:success] = t('shops.shop_successfully_listed')
          redirect_to Shop
        end
      else
        format.html do
          flash[:error] = t('shops.shop_listing_failed')
          render :new
        end
      end
    end
  end

  private

  def shop_params
    params.require(:shop).permit(
      :output_item_name, :output_amount, :input_item_name, :input_amount,
      :server_address, :world_uuid, :which, :location_x, :location_y,
      :location_z, :exchanges_available)
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/shops/_form.html.slim
= simple_form_for(shop, url: shops_path, html: {class: 'form-horizontal'}) do |f|
  = f.input :output_item_name, label: t('shops.output_item_name')
  = f.input :output_amount
  = f.input :input_item_name, label: t('shops.input_item_name')
  = f.input :input_amount
  = f.input :exchanges_available
  = f.input :world_uuid, collection: World.all.invert, label: t('shops.world')
  = f.input :location_x
  = f.input :location_y
  = f.input :location_z
  = f.input :which
  = f.submit t('shops.list_shop'), class: 'btn btn-primary'

app/views/shops/_shop.html.slim
tr
  td= shop.input_amount
  td= link_to shop.input_item_name, search_path(search: shop.input_item_name)
  td= shop.output_amount
  td= link_to shop.output_item_name, search_path(search: shop.output_item_name)
  td= shop.exchanges_available
  td= shop.location
  td.reports
    span.badge.badge-inverse= shop.reports_count
  td= link_to shop_reports_path(shop), method: :post, class: 'report btn btn-danger', title: t('reports.report') do
    i.icon-thumbs-down

app/views/shops/index.html.slim
= link_to t('shops.new_shop'), new_shop_path,
  class: 'btn btn-success pull-right'

= render 'searches/form'

table.table.table-striped
  thead
    tr
      th(colspan=2)= t('shops.input')
      th(colspan=2)= t('shops.output')
      th= t('shops.exchanges_available')
      th= t('shops.location')
      th(colspan=2)= t('reports.reports')
  tbody
    = render @shops

= paginate @shops

app/views/shops/new.html.slim
h1 New shop
= render 'form', shop: @shop